version: '3'

services:
  # ==== Application ====
  app:
    container_name: hobot
    build:
      context: ./
      dockerfile: ./.docker/Dockerfile
    env_file:
      - .env
    ports:
      - 4000:4000
    volumes:
        - ./logs/:/app/logs
        - ./assets:/app/assets
    restart: always
